title: MUSA 550 Final Project
logo: /assets/img/logo.png
description: Geospatial Data Science in Python
show_downloads: false
repository: golete/bike-bus/
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
